In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
N = 10
x = np.random.rand(N)
y = np.random.rand(N)

In [3]:
plt.plot(x, y, "o")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.show()

In [4]:
points = np.c_[x, y]

In [5]:
np.save("points2", points)

In [6]:
import sys

In [7]:
sys.path.append("./TSP/")

In [8]:
import TSP

In [9]:
dists = TSP.calc_dists(points)

In [10]:
import importlib

In [11]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [12]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=1, dists=dists)

In [13]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [14]:
tspnet.get_outputs()

array([[ 0.09252666,  0.09603535,  0.09601609,  0.10488788,  0.10933748,
         0.0915906 ,  0.09173213,  0.10804929,  0.10049763,  0.10883945],
       [ 0.10800317,  0.10597595,  0.09450281,  0.09876059,  0.10459648,
         0.10832178,  0.09536204,  0.10435161,  0.09705559,  0.10385486],
       [ 0.09980836,  0.09563059,  0.09673046,  0.10682699,  0.09300839,
         0.10090176,  0.09694141,  0.10286007,  0.10246454,  0.10801818],
       [ 0.09737951,  0.10230438,  0.09482789,  0.09520155,  0.10127095,
         0.10272718,  0.10103646,  0.09447023,  0.09469121,  0.09874009],
       [ 0.10701868,  0.09594928,  0.10306744,  0.09664603,  0.10015991,
         0.10755585,  0.10362074,  0.10285609,  0.10364068,  0.09502601],
       [ 0.10043673,  0.09786088,  0.09155825,  0.103989  ,  0.09714075,
         0.10709073,  0.09970537,  0.10710167,  0.09520529,  0.1051302 ],
       [ 0.1076868 ,  0.09756414,  0.09545878,  0.10393172,  0.09784383,
         0.10480615,  0.10723815,  0.10587071

In [15]:
np.sum(tspnet.get_outputs())

10.039678531678726

In [16]:
plt.imshow(np.eye(10), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [17]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   9.79088125e-248,   0.00000000e+000,
          0.00000000e+000,   1.82344369e-038,   1.25614581e-221,
          2.45811790e-245,   3.72510489e-105,   0.00000000e+000,
          1.99174390e-150],
       [  1.87484504e-288,   0.00000000e+000,   3.70863921e-048,
          1.15785408e-260,   0.00000000e+000,   3.86323024e-227,
          1.17835076e-078,   1.79554558e-033,   1.00000000e+000,
          1.30083932e-102],
       [  5.60090063e-073,   6.12641035e-105,   4.87008339e-061,
          8.54659091e-178,   2.03669029e-063,   2.83344144e-096,
          1.50863145e-115,   4.43757681e-241,   3.17483139e-032,
          1.00000000e+000],
       [  7.31817957e-285,   1.43251185e-190,   5.59663561e-060,
          2.01711473e-285,   3.12432866e-065,   6.18374838e-269,
          8.25702109e-035,   6.84960222e-062,   1.00000000e+000,
          1.91471893e-068],
       [  1.90906087e-251,   7.05323084e-292,   1.36525084e-167,
          1.03898273e-093,   2.78029919e-19

In [18]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=1, dists=dists)

In [19]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [20]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  0.00000000e+000,   2.93168628e-075,   1.00000000e+000,
          2.66143559e-271,   7.14010255e-121,   4.36621637e-230,
          1.00004599e-125,   5.73832039e-118,   1.07001199e-234,
          1.72191083e-066],
       [  3.52144288e-153,   0.00000000e+000,   4.73970231e-306,
          9.51611993e-228,   0.00000000e+000,   8.38533014e-264,
          1.00000000e+000,   5.11977100e-080,   9.90842535e-275,
          0.00000000e+000],
       [  3.09528475e-060,   2.00621654e-239,   2.47748893e-164,
          1.93900748e-249,   1.27587054e-133,   6.39803503e-256,
          2.22373253e-283,   5.52298702e-099,   2.83299462e-296,
          1.00000000e+000],
       [  1.00000000e+000,   0.00000000e+000,   2.79848067e-091,
          2.12656794e-101,   0.00000000e+000,   0.00000000e+000,
          1.83314921e-183,   1.00000000e+000,   2.24374722e-096,
          1.81255681e-125],
       [  8.45753828e-189,   8.32747921e-285,   1.22722646e-216,
          9.04732788e-223,   1.00000000e+00

In [21]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [22]:
tspnet.log

[array([[  0.00000000e+000,   2.93168628e-075,   1.00000000e+000,
           2.66143559e-271,   7.14010255e-121,   4.36621637e-230,
           1.00004599e-125,   5.73832039e-118,   1.07001199e-234,
           1.72191083e-066],
        [  3.52144288e-153,   0.00000000e+000,   4.73970231e-306,
           9.51611993e-228,   0.00000000e+000,   8.38533014e-264,
           1.00000000e+000,   5.11977100e-080,   9.90842535e-275,
           0.00000000e+000],
        [  3.09528475e-060,   2.00621654e-239,   2.47748893e-164,
           1.93900748e-249,   1.27587054e-133,   6.39803503e-256,
           2.22373253e-283,   5.52298702e-099,   2.83299462e-296,
           1.00000000e+000],
        [  1.00000000e+000,   0.00000000e+000,   2.79848067e-091,
           2.12656794e-101,   0.00000000e+000,   0.00000000e+000,
           1.83314921e-183,   1.00000000e+000,   2.24374722e-096,
           1.81255681e-125],
        [  8.45753828e-189,   8.32747921e-285,   1.22722646e-216,
           9.04732788e-223

In [23]:
import matplotlib.animation as animation

In [24]:
len(tspnet.log)

100

In [25]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [26]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=1, dists=dists)

In [27]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   1.29914466e-227,   0.00000000e+000,
          0.00000000e+000,   1.11489064e-115,   1.49266576e-015,
          0.00000000e+000,   7.61055099e-088,   1.00000000e+000,
          7.47163383e-159],
       [  1.00368239e-174,   1.67979272e-099,   6.72398763e-289,
          0.00000000e+000,   0.00000000e+000,   4.51183518e-195,
          1.00000000e+000,   4.39721014e-183,   5.01848364e-149,
          1.46590044e-204],
       [  1.43960691e-135,   3.91187198e-048,   1.00000000e+000,
          2.50483215e-205,   0.00000000e+000,   0.00000000e+000,
          3.33730379e-151,   4.41842845e-259,   3.38488777e-265,
          0.00000000e+000],
       [  1.50966339e-095,   1.00000000e+000,   0.00000000e+000,
          2.38118876e-290,   4.59691354e-269,   1.94285815e-300,
          2.23110426e-215,   8.30058990e-096,   0.00000000e+000,
          1.00000000e+000],
       [  3.58400811e-150,   4.35892845e-198,   0.00000000e+000,
          0.00000000e+000,   3.01367245e-30

In [29]:
log = tspnet.log

In [30]:
log

[array([[ 0.10095357,  0.09776982,  0.09798804,  0.09200903,  0.09642319,
          0.10015759,  0.10260081,  0.10536542,  0.09903155,  0.10775564],
        [ 0.10404282,  0.1017455 ,  0.09210982,  0.10408696,  0.10285551,
          0.10899851,  0.09278728,  0.10875011,  0.10886206,  0.09883131],
        [ 0.09395294,  0.09228733,  0.1017814 ,  0.10117007,  0.09492158,
          0.09555684,  0.10466287,  0.09830242,  0.09414391,  0.09349762],
        [ 0.10916926,  0.09637536,  0.09330366,  0.09309677,  0.10125664,
          0.10376911,  0.10320873,  0.10143947,  0.09826195,  0.09550543],
        [ 0.10416009,  0.10106566,  0.10251082,  0.10453507,  0.09870189,
          0.0925526 ,  0.09346385,  0.09603868,  0.10785475,  0.10532223],
        [ 0.0974249 ,  0.09732961,  0.10478625,  0.10405141,  0.10921478,
          0.10194789,  0.0952676 ,  0.09579128,  0.09739739,  0.10485551],
        [ 0.09385104,  0.10618444,  0.09213192,  0.09859254,  0.09802142,
          0.09226658,  0.1035126

In [31]:
for i in range(10):
    plt.imshow(log[i], cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
    plt.colorbar()
    plt.show()

In [32]:
fig2 = plt.figure()

ims = []
for frame in log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [33]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   6.25751974e-113,
          0.00000000e+000],
       [  4.47574290e-234,   1.51477425e-237,   4.27564533e-260,
          2.07704261e-245,   1.36700891e-240,   0.00000000e+000,
          1.00000000e+000,   8.79644783e-202,   0.00000000e+000,
          0.00000000e+000],
       [  1.92395229e-248,   1.71672440e-184,   1.00000000e+000,
          1.39211108e-233,   1.17388368e-293,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  9.01618804e-305,   1.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+00

In [34]:
tspnet.log

[array([[ 0.10095357,  0.09776982,  0.09798804,  0.09200903,  0.09642319,
          0.10015759,  0.10260081,  0.10536542,  0.09903155,  0.10775564],
        [ 0.10404282,  0.1017455 ,  0.09210982,  0.10408696,  0.10285551,
          0.10899851,  0.09278728,  0.10875011,  0.10886206,  0.09883131],
        [ 0.09395294,  0.09228733,  0.1017814 ,  0.10117007,  0.09492158,
          0.09555684,  0.10466287,  0.09830242,  0.09414391,  0.09349762],
        [ 0.10916926,  0.09637536,  0.09330366,  0.09309677,  0.10125664,
          0.10376911,  0.10320873,  0.10143947,  0.09826195,  0.09550543],
        [ 0.10416009,  0.10106566,  0.10251082,  0.10453507,  0.09870189,
          0.0925526 ,  0.09346385,  0.09603868,  0.10785475,  0.10532223],
        [ 0.0974249 ,  0.09732961,  0.10478625,  0.10405141,  0.10921478,
          0.10194789,  0.0952676 ,  0.09579128,  0.09739739,  0.10485551],
        [ 0.09385104,  0.10618444,  0.09213192,  0.09859254,  0.09802142,
          0.09226658,  0.1035126

In [35]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [36]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   5.98684240e-113,   5.57293160e-049,
          4.21882972e-213,   9.11608720e-161,   2.02638256e-250,
          0.00000000e+000,   3.40280150e-200,   5.33111402e-247,
          5.16486327e-066],
       [  1.56085435e-162,   5.22436467e-166,   1.34848940e-188,
          2.20930625e-245,   4.65539758e-169,   4.51526769e-143,
          1.00000000e+000,   2.99702709e-150,   1.03032976e-197,
          1.12670473e-226],
       [  6.70952144e-177,   5.98684240e-113,   1.00000000e+000,
          4.85479770e-162,   4.09375937e-222,   1.27190854e-243,
          1.65965275e-297,   1.07482842e-229,   2.04604998e-235,
          5.62733457e-245],
       [  3.10962866e-233,   1.00000000e+000,   2.68642386e-259,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.00000000e+000],
       [  3.07326701e-199,   1.16271207e-209,   1.00140974e-222,
          1.53627815e-152,   2.24088984e-11

In [37]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [38]:
tspnet.update(epoch=1, logging=True)    

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   5.98684240e-113,   1.76700529e-120,
          4.21882972e-213,   2.89043101e-232,   2.02638256e-250,
          0.00000000e+000,   3.40280150e-200,   5.33111402e-247,
          5.16486327e-066],
       [  1.56085435e-162,   5.22436467e-166,   1.34848940e-188,
          6.96789800e-174,   1.47608346e-240,   4.51526769e-143,
          1.00000000e+000,   2.99702709e-150,   1.03032976e-197,
          1.12670473e-226],
       [  6.70952144e-177,   5.98684240e-113,   1.00000000e+000,
          4.85479770e-162,   4.09375937e-222,   1.27190854e-243,
          1.65965275e-297,   0.00000000e+000,   2.04604998e-235,
          5.62733457e-245],
       [  3.10962866e-233,   1.00000000e+000,   2.68642386e-259,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.00000000e+000],
       [  3.07326701e-199,   1.16271207e-209,   1.00140974e-222,
          1.53627815e-152,   2.24088984e-11

In [39]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [40]:
np.sum(tspnet.outputs)

11.0

In [41]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   1.37166590e-097,   1.27683339e-033,
          1.33766121e-284,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   1.44313768e-256,   0.00000000e+000,
          1.63761937e-137],
       [  3.57612669e-147,   1.65648543e-237,   4.27564533e-260,
          2.20930625e-245,   1.00000000e+000,   0.00000000e+000,
          1.58299875e-032,   0.00000000e+000,   3.26685892e-269,
          3.57243434e-298],
       [  2.12738299e-248,   1.89824368e-184,   1.00000000e+000,
          1.53930711e-233,   1.29800525e-293,   0.00000000e+000,
          0.00000000e+000,   3.67548395e-299,   6.48739551e-307,
          0.00000000e+000],
       [  9.85967654e-305,   1.00000000e+000,   6.15495744e-244,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   9.19086458e-27

In [42]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [43]:
tspnet.update(epoch=1, logging=True)

epoch 0


./TSP/TSP.py:124: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(u / u_0)))


array([[  1.00000000e+000,   1.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.18333946e-050],
       [  4.94898930e-234,   0.00000000e+000,   0.00000000e+000,
          2.20930625e-245,   1.00000000e+000,   2.82504400e-208,
          1.12781955e-249,   0.00000000e+000,   3.26685892e-269,
          2.58143168e-211],
       [  7.44257113e-265,   0.00000000e+000,   3.12728476e-069,
          7.00957064e-053,   9.37935187e-207,   3.79319052e-306,
          0.00000000e+000,   0.00000000e+000,   6.48739551e-307,
          0.00000000e+000],
       [  6.25751974e-113,   4.36208414e-063,   6.15495744e-244,
          0.00000000e+000,   1.37511141e-225,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   4.44218357e-268,
          1.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   9.19086458e-27

In [44]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
#im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [46]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
im_ani.save('im.mp4', metadata={'artist':'Guido'})

plt.show()

In [66]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [81]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)

In [82]:
np.sum(tspnet.outputs)

9.9924410331293618

In [83]:
plt.imshow(tspnet.outputs, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.show()

In [85]:
x = np.arange(-10, 10, 0.1)

In [87]:
plt.plot(x, TSP.sigmoid(x, u_0=10))
plt.show()

In [88]:
tspnet.update(logging=True)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


array([[  8.81080581e-16,   8.62852376e-22,   8.51902834e-06,
          1.00000000e+00,   7.68507335e-42,   2.77986300e-61,
          2.88039926e-69,   6.11184819e-62,   3.87044218e-38,
          2.60262377e-40],
       [  1.00000000e+00,   1.38691870e-20,   6.32097206e-35,
          5.14267746e-31,   5.82702118e-42,   2.69666265e-35,
          3.81883784e-33,   5.40979134e-46,   4.99529068e-34,
          7.43354874e-22],
       [  3.25836103e-43,   1.52214200e-31,   3.50822904e-36,
          4.10503522e-21,   1.00000000e+00,   5.22571766e-34,
          2.48738394e-49,   3.36814107e-63,   5.95449127e-48,
          2.38828764e-40],
       [  3.07720550e-11,   1.00000000e+00,   8.51902831e-06,
          5.07292293e-22,   6.78722643e-42,   5.34640508e-53,
          3.25676385e-59,   2.69106148e-54,   1.25982480e-33,
          9.44520295e-33],
       [  3.23548296e-76,   9.41206923e-66,   4.22919162e-78,
          6.76305190e-75,   3.51300004e-54,   5.22571766e-34,
          1.00000000e+00

In [89]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
im_ani.save('im2.mp4', metadata={'artist':'Guido'})

plt.show()

In [90]:
tspnet.outputs

array([[  8.81080581e-16,   8.62852376e-22,   8.51902834e-06,
          1.00000000e+00,   7.68507335e-42,   2.77986300e-61,
          2.88039926e-69,   6.11184819e-62,   3.87044218e-38,
          2.60262377e-40],
       [  1.00000000e+00,   1.38691870e-20,   6.32097206e-35,
          5.14267746e-31,   5.82702118e-42,   2.69666265e-35,
          3.81883784e-33,   5.40979134e-46,   4.99529068e-34,
          7.43354874e-22],
       [  3.25836103e-43,   1.52214200e-31,   3.50822904e-36,
          4.10503522e-21,   1.00000000e+00,   5.22571766e-34,
          2.48738394e-49,   3.36814107e-63,   5.95449127e-48,
          2.38828764e-40],
       [  3.07720550e-11,   1.00000000e+00,   8.51902831e-06,
          5.07292293e-22,   6.78722643e-42,   5.34640508e-53,
          3.25676385e-59,   2.69106148e-54,   1.25982480e-33,
          9.44520295e-33],
       [  3.23548296e-76,   9.41206923e-66,   4.22919162e-78,
          6.76305190e-75,   3.51300004e-54,   5.22571766e-34,
          1.00000000e+00

In [93]:
epsilon = 0.1
outputs = tspnet.outputs.copy().astype(np.int64)
for i in range(N):
    for j in range(N):
        x = outputs[i][j]
        if x > 1 - epsilon:
            outputs[i][j] = 1
        elif x < epsilon:
            outputs[i][j] = 0
        else:
            raise NameError('cannot decide')

In [94]:
outputs

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [95]:
outputs[:, 0]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
route = []
for i in range(N):
    col = outputs[:, i]
    for j in range(N):
        if col[j] == 1:
            route.append(j)

In [98]:
route

[1, 3, 5, 0, 2, 7, 4, 6, 9, 8]

In [99]:
len(route)

10

In [107]:
route.append(route[0])

In [109]:
plt.plot(points[:, 0], points[:, 1], "o")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route])
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.show()

In [114]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [115]:
outputs

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [116]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)

In [117]:
tspnet.is_permutation(outputs)

True

In [118]:
tspnet.is_permutation(np.eye(10))

True

In [119]:
tspnet.is_permutation(tspnet.outputs)

False

In [120]:
route

[1, 3, 5, 0, 2, 7, 4, 6, 9, 8, 1]

In [121]:
dist1 = TSP.calc_route_dist(dists, route)

In [122]:
dist1

3.4427477755890443

In [123]:
tspnet.update(logging=True)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


array([[  1.39428863e-71,   1.63158918e-73,   1.18960604e-76,
          1.18940015e-55,   2.95941949e-69,   3.21509383e-65,
          9.69673130e-84,   1.03998369e-63,   1.00000000e+00,
          1.00000000e+00],
       [  1.90541538e-74,   3.76335160e-77,   1.54469625e-69,
          1.40953073e-86,   6.27164314e-80,   5.16637983e-64,
          1.00000000e+00,   1.00000000e+00,   1.03998369e-63,
          3.85624672e-74],
       [  1.00000000e+00,   3.93196955e-27,   1.25655270e-37,
          1.61631038e-47,   5.34459235e-46,   1.52422608e-31,
          2.38989497e-40,   1.57247646e-30,   1.57247646e-30,
          4.24078125e-20],
       [  3.49308840e-28,   2.55555478e-27,   4.09393171e-23,
          1.00000000e+00,   4.17380462e-18,   1.38877117e-20,
          9.45961487e-33,   1.93373613e-20,   1.93373614e-20,
          7.07506004e-22],
       [  2.12173121e-12,   7.04788317e-30,   2.08695393e-07,
          1.74691754e-37,   3.02641094e-23,   2.53556977e-22,
          3.41082051e-11

In [124]:
fig2 = plt.figure()

ims = []
for frame in tspnet.log:
    ims.append((plt.imshow(frame, cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest"),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
im_ani.save('im3.mp4', metadata={'artist':'Guido'})

plt.show()

In [125]:
route = tspnet.decide_route()

NameError: name 'N' is not defined

In [126]:
tspnet.update(logging=True)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


array([[  1.39428863e-71,   1.63158918e-73,   1.18960604e-76,
          1.18940015e-55,   2.95941949e-69,   3.21509383e-65,
          9.69673130e-84,   1.03998369e-63,   1.00000000e+00,
          1.00000000e+00],
       [  1.90541538e-74,   3.76335160e-77,   1.54469625e-69,
          1.40953073e-86,   6.27164314e-80,   5.16637983e-64,
          1.00000000e+00,   1.00000000e+00,   1.03998369e-63,
          3.85624672e-74],
       [  1.00000000e+00,   3.93196955e-27,   1.25655270e-37,
          1.61631038e-47,   5.34459235e-46,   1.52422608e-31,
          2.38989497e-40,   1.57247646e-30,   1.57247646e-30,
          4.24078125e-20],
       [  3.49308840e-28,   2.55555478e-27,   4.09393171e-23,
          1.00000000e+00,   4.17380462e-18,   1.38877117e-20,
          9.45961487e-33,   1.93373613e-20,   1.93373614e-20,
          7.07506004e-22],
       [  2.12173121e-12,   7.04788317e-30,   2.08695393e-07,
          1.74691754e-37,   3.02641094e-23,   2.53556977e-22,
          3.41082051e-11

In [127]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [128]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [129]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)

In [130]:
tspnet.is_permutation(tspnet.outputs)

False

In [131]:
tspnet.update(logging=True)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


array([[  8.07983834e-097,   2.37969431e-064,   4.52449569e-031,
          2.01244131e-010,   1.00000000e+000,   8.56093499e-030,
          1.88801222e-038,   1.67984819e-057,   6.84213076e-056,
          3.99708084e-070],
       [  1.11017932e-052,   1.71816671e-053,   3.37818726e-013,
          2.43445103e-048,   1.50208631e-089,   9.40068576e-059,
          1.78155004e-031,   1.00000000e+000,   1.19638599e-019,
          3.53493075e-054],
       [  3.62357307e-073,   1.23325405e-062,   4.87757567e-025,
          1.09188882e-048,   7.92047828e-095,   1.13833208e-048,
          1.00000000e+000,   4.20870743e-038,   3.66912369e-040,
          2.20087022e-071],
       [  2.03602830e-084,   1.02053754e-097,   9.09846851e-011,
          1.00000000e+000,   7.48656235e-063,   2.83094565e-035,
          4.56108486e-034,   2.26003197e-042,   6.05897760e-046,
          1.75992429e-062],
       [  1.00000000e+000,   4.70284659e-001,   2.09129302e-034,
          1.92452206e-111,   2.96133866e-14

In [134]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [135]:
tspnet.update()

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9


array([[  1.19314582e-086,   1.78678522e-061,   6.37669800e-047,
          2.72165246e-020,   1.00000000e+000,   5.42240147e-039,
          3.00959589e-012,   1.52935659e-057,   4.63352718e-047,
          5.95926460e-062],
       [  1.58052757e-050,   7.08497741e-025,   1.00000000e+000,
          2.71456764e-020,   6.00422703e-038,   5.95429021e-068,
          3.56975933e-043,   2.51113459e-032,   2.39722316e-031,
          5.27024309e-046],
       [  1.02946997e-066,   8.01964388e-062,   1.32601215e-044,
          1.53088336e-030,   3.17431002e-043,   7.21006947e-058,
          1.00000000e+000,   5.86791563e-030,   5.78956381e-042,
          3.28125820e-063],
       [  3.17545805e-059,   6.05298755e-069,   7.73607598e-037,
          1.00000000e+000,   3.00038242e-011,   6.88791977e-022,
          1.78055023e-016,   1.33866043e-051,   2.37332503e-028,
          1.11471657e-071],
       [  1.00000000e+000,   3.00994941e-042,   1.43008860e-066,
          2.56126669e-124,   4.98151897e-13

In [138]:
plt.imshow(tspnet.get_outputs(), cmap=plt.cm.gray_r, vmin=0, vmax=1, interpolation="nearest")
plt.colorbar()
plt.show()

In [143]:
tspnet.outputs[0]

array([  1.19314582e-86,   1.78678522e-61,   6.37669800e-47,
         2.72165246e-20,   1.00000000e+00,   5.42240147e-39,
         3.00959589e-12,   1.52935659e-57,   4.63352718e-47,
         5.95926460e-62])

In [144]:
outputs = tspnet.outputs

In [145]:
outputs

array([[  1.19314582e-086,   1.78678522e-061,   6.37669800e-047,
          2.72165246e-020,   1.00000000e+000,   5.42240147e-039,
          3.00959589e-012,   1.52935659e-057,   4.63352718e-047,
          5.95926460e-062],
       [  1.58052757e-050,   7.08497741e-025,   1.00000000e+000,
          2.71456764e-020,   6.00422703e-038,   5.95429021e-068,
          3.56975933e-043,   2.51113459e-032,   2.39722316e-031,
          5.27024309e-046],
       [  1.02946997e-066,   8.01964388e-062,   1.32601215e-044,
          1.53088336e-030,   3.17431002e-043,   7.21006947e-058,
          1.00000000e+000,   5.86791563e-030,   5.78956381e-042,
          3.28125820e-063],
       [  3.17545805e-059,   6.05298755e-069,   7.73607598e-037,
          1.00000000e+000,   3.00038242e-011,   6.88791977e-022,
          1.78055023e-016,   1.33866043e-051,   2.37332503e-028,
          1.11471657e-071],
       [  1.00000000e+000,   3.00994941e-042,   1.43008860e-066,
          2.56126669e-124,   4.98151897e-13

In [153]:
importlib.reload(TSP)

<module 'TSP' from './TSP/TSP.py'>

In [154]:
tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)

In [155]:
tspnet.outputs = outputs

In [156]:
route = tspnet.decide_route()

In [157]:
route

[4, 7, 1, 3, 8, 2, 5, 9, 6, 4]

In [166]:
plt.plot(points[:, 0], points[:, 1], "o", color="r")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route], color="b")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.xlabel("total = "+ str(dist2), fontsize=20)
plt.savefig("result1.png")
plt.show()

In [160]:
dist1

3.4427477755890443

In [161]:
dist2 = TSP.calc_route_dist(dists, route)

In [162]:
dist2

3.6499035048370865

In [167]:
route = [1, 3, 5, 0, 2, 7, 4, 6, 9, 8, 1]

In [168]:
plt.plot(points[:, 0], points[:, 1], "o", color="r")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route], color="b")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.xlabel("total = "+ str(dist1), fontsize=20)
plt.savefig("result2.png")
plt.show()

In [170]:
route = np.random.permutation(N)

In [173]:
route = route.tolist()

In [175]:
route.append(route[0])

In [176]:
route

[5, 0, 8, 1, 3, 2, 4, 9, 6, 7, 5]

In [177]:
plt.plot(points[:, 0], points[:, 1], "o", color="r")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route], color="b")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.xlabel("total = "+ str(TSP.calc_route_dist(dists, route)), fontsize=20)
plt.savefig("random_route.png")
plt.show()

In [179]:
np.savetxt("dists1.txt", dists)

In [180]:
route = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [181]:
plt.plot(points[:, 0], points[:, 1], "o", color="r")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route], color="b")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.xlabel("total = "+ str(TSP.calc_route_dist(dists, route)), fontsize=20)
plt.savefig("minimum_route.png")
plt.show()

In [182]:
route = [0, 5, 8, 9, 6, 4, 7, 1, 2, 3, 0]

In [183]:
plt.plot(points[:, 0], points[:, 1], "o", color="r")
plt.plot([points[i, 0] for i in route], [points[i, 1] for i in route], color="b")
plt.xlim(-0.2, 1.2)
plt.ylim(-0.2, 1.2)
plt.axes().set_aspect('equal')
plt.xlabel("total = "+ str(TSP.calc_route_dist(dists, route)), fontsize=20)
plt.savefig("minimum_route.png")
plt.show()

In [187]:
route.clear()

In [188]:
import itertools

In [201]:
totals = []
for i in itertools.permutations(range(1, 10)):
    route = list(i)
    route.insert(0, 0)
    route.append(0)
    totals.append(TSP.calc_route_dist(dists, route))

In [202]:
totals

[5.5440857014588403,
 5.1601461944785862,
 6.331614655385204,
 6.1298651929183858,
 5.9411574684411024,
 6.1233475129545383,
 5.5123604670773823,
 5.1219032801332807,
 6.2933717410398984,
 6.1312193159642217,
 5.9094322340596444,
 6.1377369959280692,
 5.2920298033317223,
 5.8712916148274212,
 5.2855121233678748,
 5.9108886522185617,
 5.0837626609010576,
 5.1298773782560465,
 5.2920509596109317,
 6.2617699580507313,
 5.2985686395747793,
 6.3078846754057203,
 5.4807586840882152,
 5.5203557214793566,
 5.5093949704027452,
 5.1254554634224911,
 5.2890643066570853,
 5.087314844190268,
 5.2956031429001422,
 5.4777931874135781,
 4.4698101183492636,
 4.4763489545923205,
 4.6399577978269146,
 4.3026630246981634,
 4.2560182908466606,
 3.9121846814748529,
 5.2573390722756272,
 5.2257372892864611,
 5.6478174154989382,
 5.0901919786245271,
 5.4460679530321201,
 4.920044299146876,
 5.2573602285548366,
 5.2192196093226126,
 4.8668818853315257,
 4.6931959554373686,
 5.0490719298449616,
 4.9135266191830

In [203]:
len(totals)

362880

In [204]:
plt.hist(totals)

(array([   200.,   2934.,  13700.,  37522.,  68662.,  88260.,  81192.,
         50984.,  17192.,   2234.]),
 array([ 2.80186949,  3.22839075,  3.65491201,  4.08143327,  4.50795453,
         4.93447579,  5.36099705,  5.78751831,  6.21403957,  6.64056083,
         7.0670821 ]),
 <a list of 10 Patch objects>)

In [205]:
plt.show()

In [214]:
plt.hist(totals)
plt.annotate('min', xy=(2.8, 0), xytext=(2.8, 10000), fontsize=20, arrowprops=dict(facecolor='black', shrink=0.05))
plt.savefig("total.png")

In [215]:
plt.show()

In [217]:
a = None

In [223]:
results = []
for i in range(100):
    tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)
    tspnet.update()
    try:
        route = tspnet.decide_route()
        route.append(route[0])
        results.append(TSP.calc_route_dist(dists, route))
    except:
        results.append(False)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4


In [224]:
results

[False,
 False,
 False,
 3.8172563374187973,
 False,
 False,
 False,
 3.6285980261156272,
 False,
 False,
 False,
 2.8586658984998268,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 3.4993884220894609,
 3.7163340977261332,
 False,
 3.7017664228140221,
 False,
 False,
 False,
 3.8395650618334844,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 4.2957045184648512,
 False,
 3.8834918950342274,
 False,
 False,
 False,
 False,
 3.9086325848497991,
 3.3860247090902895,
 False,
 False,
 4.6849092475478002,
 False,
 False,
 3.6404339243726063,
 4.0613441748519277,
 False,
 3.586250321366188,
 False,
 False,
 False,
 False,
 4.4382360616681105,
 3.9821324631001231,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 3.5567650020256636,
 False,
 False,
 False,
 False,
 False,
 False,
 4.4397012745385984,
 False,
 False,
 False,
 3.5155758101185377,
 4.1528230091292713,
 False,


In [225]:
min(results)

False

In [232]:
results2 = []
for i in results:
    if i:
        results2.append(i)

In [233]:
len(results2)

24

In [234]:
results2

[3.8172563374187973,
 3.6285980261156272,
 2.8586658984998268,
 3.4993884220894609,
 3.7163340977261332,
 3.7017664228140221,
 3.8395650618334844,
 4.2957045184648512,
 3.8834918950342274,
 3.9086325848497991,
 3.3860247090902895,
 4.6849092475478002,
 3.6404339243726063,
 4.0613441748519277,
 3.586250321366188,
 4.4382360616681105,
 3.9821324631001231,
 3.5567650020256636,
 4.4397012745385984,
 3.5155758101185377,
 4.1528230091292713,
 4.3211230182684899,
 3.4989748165878471,
 4.4759991373230008]

In [235]:
min(results2)

2.8586658984998268

In [236]:
plt.hist(results2)

(array([ 1.,  0.,  1.,  5.,  4.,  4.,  2.,  2.,  4.,  1.]),
 array([ 2.8586659 ,  3.04129023,  3.22391457,  3.4065389 ,  3.58916324,
         3.77178757,  3.95441191,  4.13703624,  4.31966058,  4.50228491,
         4.68490925]),
 <a list of 10 Patch objects>)

In [237]:
plt.show()

In [ ]:
results = []
for i in range(10000):
    tspnet = TSP.TSPNetwork(size=N, A=500, B=500, C=200, D=500, n=15, u_0=10, dists=dists)
    tspnet.update()
    try:
        route = tspnet.decide_route()
        route.append(route[0])
        results.append(TSP.calc_route_dist(dists, route))
    except:
        results.append(False)

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
